CREATE TABLE Movie (id INTEGER NOT NULL PRIMARY KEY, title VARCHAR(100) NOT NULL, year INTEGER NOT NULL, rating VARCHAR(10), company VARCHAR(50) NOT NULL) ENGINE = InnoDB;

CREATE TABLE Actor (id INTEGER NOT NULL PRIMARY KEY, last VARCHAR(20) NOT NULL, first VARCHAR(20) NOT NULL, sex VARCHAR(6) NOT NULL, dob DATE NOT NULL, dod DATE DEFAULT NULL) ENGINE = InnoDB;

CREATE TABLE Director (id INTEGER NOT NULL PRIMARY KEY, last VARCHAR(20) NOT NULL, first VARCHAR(20) NOT NULL, dob DATE NOT NULL, dod DATE DEFAULT NULL) ENGINE = InnoDB;

CREATE TABLE MovieGenre (mid INTEGER REFERENCES Movie(id), genre VARCHAR(20), FOREIGN KEY (mid) REFERENCES Movie(id)) ENGINE = InnoDB;

CREATE TABLE MovieDirector (mid INTEGER REFERENCES Movie(id), did INTEGER REFERENCES Director(id), FOREIGN KEY (mid) REFERENCES Movie(id), FOREIGN KEY (did) REFERENCES Director(id)) ENGINE = InnoDB;

CREATE TABLE MovieActor (mid INTEGER REFERENCES Movie(id), aid INTEGER REFERENCES Actor(id), role VARCHAR(50), FOREIGN KEY (mid) REFERENCES Movie(id), FOREIGN KEY (aid) REFERENCES Actor(id)) ENGINE = InnoDB;

CREATE TABLE Review (name VARCHAR(20), time TIMESTAMP, mid INTEGER REFERENCES Movie(id), rating INTEGER, comment VARCHAR(500), FOREIGN KEY(mid) REFERENCES Movie(id)) ENGINE = InnoDB;

CREATE TABLE MaxPersonID (id INTEGER DEFAULT 69000) ENGINE = InnoDB;

CREATE TABLE MaxMovieID (id INTEGER DEFAULT 4750) ENGINE = InnoDB;